name: personalportfoliotracker

services:
  db:
    image: mariadb:11.4.5
    container_name: personalportfoliotracker_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_USER_FILE: /run/secrets/db_user
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_DATABASE_FILE: /run/secrets/db_name
    secrets:
      - db_root_password
      - db_user
      - db_password
      - db_name
    volumes:
      - db_vol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./PersonalPortfolioTrackerBackend/PersonalPortfolioTracker
      dockerfile: Dockerfile
    container_name: personalportfoliotracker_backend
    restart: always
    ports:
      - "5001:5000"
    secrets:
      - personal_portfolio_tracker_db_connection_string
      - personal_portfolio_tracker_frontend
      - stock_search_api_path
      - stock_search_api_token
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5000/healthcheck"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./personal-portfolio-tracker-frontend
      dockerfile: Dockerfile
    container_name: personalportfoliotracker_frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      backend:
        condition: service_healthy

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_name:
    file: ./secrets/db_name.txt
  personal_portfolio_tracker_db_connection_string:
    file: ./secrets/personal_portfolio_tracker_db_connection_string.txt
  personal_portfolio_tracker_frontend:
    file: ./secrets/personal_portfolio_tracker_frontend.txt
  stock_search_api_path:
    file: ./secrets/stock_search_api_path.txt
  stock_search_api_token:
    file: ./secrets/stock_search_api_token.txt

volumes:
  db_vol: