# Dockerfile
FROM node:22.14.0 AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
COPY .env .
RUN npm run build

FROM nginx:stable

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
